"use client";

import { useCallback, useEffect, useState } from "react";
import { Download, Plus, Search, X } from "lucide-react";
import { SuratForm } from "@/components/surat/SuratForm";
import { SuratTable } from "@/components/surat/SuratTable";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSpinner } from "@/components/ui/LoadingSpinner";
import { fetchJson } from "@/lib/utils";
import { useFeedback } from "@/stores/feedback";
import type { Aset, Surat } from "@/types";

interface Bootstrap { riwayat: Surat[]; aset: Aset[] }
export default function SuratPage() {
  const showFeedback = useFeedback((state) => state.show);
  const [data, setData] = useState<Bootstrap | null>(null); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Surat>(); const [deleting, setDeleting] = useState("");
  const load = useCallback(async () => { try { const result = await fetchJson<Bootstrap>("/api/bootstrap"); setData(result); setError(""); const edit = new URLSearchParams(window.location.search).get("edit"); if (edit) { const detail = await fetchJson<Surat>(`/api/surat/${encodeURIComponent(edit)}`); setEditing(detail); setFormOpen(true); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Data gagal dimuat."); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function remove(nomor: string) { if (!window.confirm(`Hapus surat ${nomor}? Tindakan ini tidak dapat dibatalkan.`)) return; setDeleting(nomor); try { await fetchJson(`/api/surat/${encodeURIComponent(nomor)}`, { method: "DELETE" }); setData((current) => current ? { ...current, riwayat: current.riwayat.filter((item) => item.nomor !== nomor) } : current); showFeedback("Surat berhasil dihapus."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Surat gagal dihapus."); } finally { setDeleting(""); } }
  const filtered = (data?.riwayat ?? []).filter((item) => `${item.nomor} ${item.nama} ${item.penerima}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:py-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-700">Dokumen</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Riwayat surat</h1><p className="mt-2 text-sm text-slate-600">Buat, lacak, dan lengkapi surat serah terima.</p></div><div className="flex flex-wrap gap-2"><a href="/api/riwayat/download" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-white px-4 text-sm font-semibold text-slate-700 ring-1 ring-slate-300 focus-visible:outline-2 focus-visible:outline-blue-700"><Download className="size-4"/>Export Excel</a><Button onClick={() => { setEditing(undefined); setFormOpen(true); }}><Plus className="size-4"/>Buat surat</Button></div></header>{formOpen && <section aria-labelledby="judul-form-surat" className="mt-7 rounded-2xl border border-blue-100 bg-white p-5 shadow-lg sm:p-7"><div className="mb-6 flex items-center justify-between"><h2 id="judul-form-surat" className="text-xl font-bold">{editing ? "Edit surat" : "Surat baru"}</h2><button aria-label="Tutup formulir" className="grid size-11 place-items-center rounded-lg hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-blue-700" onClick={() => setFormOpen(false)}><X className="size-5"/></button></div><SuratForm assets={data?.aset ?? []} initial={editing} onCancel={() => setFormOpen(false)} onSaved={(surat) => { setData((current) => current ? { ...current, riwayat: editing ? current.riwayat.map((item) => item.nomor === surat.nomor ? surat : item) : [surat, ...current.riwayat] } : current); setFormOpen(false); showFeedback(editing ? "Perubahan berhasil disimpan." : "Surat berhasil dibuat."); }}/></section>}<section className="mt-7" aria-label="Daftar surat"><label className="relative block max-w-md"><span className="sr-only">Cari surat</span><Search className="pointer-events-none absolute left-3 top-3.5 size-4 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nomor atau nama…" className="min-h-11 w-full rounded-lg border border-slate-300 bg-white pl-10 pr-3 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100"/></label><div className="mt-4">{error ? <ErrorState message={error} retry={load}/> : !data ? <LoadingSpinner label="Memuat riwayat"/> : filtered.length ? <SuratTable data={filtered} deleting={deleting} onDelete={remove}/> : <EmptyState title={query ? "Tidak ada hasil" : "Belum ada surat"} description={query ? "Coba kata kunci yang berbeda." : "Buat surat pertama untuk memulai riwayat."} action={!query && <Button onClick={() => setFormOpen(true)}><Plus className="size-4"/>Buat surat</Button>}/>}</div></section></main>;
}
