"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Save } from "lucide-react";
import { z } from "zod";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { fetchJson } from "@/lib/utils";
import { suratSchema } from "@/lib/schemas";
import type { Aset, Surat } from "@/types";

type Values = z.input<typeof suratSchema>;
const departments = ["IT", "Keuangan", "HRD", "Umum", "Pemasaran", "Produksi", "Gudang"];

export function SuratForm({ assets, initial, onSaved, onCancel }: { assets: Aset[]; initial?: Surat; onSaved: (surat: Surat) => void; onCancel?: () => void }) {
  const { register, handleSubmit, formState: { errors, isSubmitting }, setError } = useForm<Values>({ resolver: zodResolver(suratSchema), defaultValues: { nama: initial?.nama ?? "", departemen: initial?.departemen ?? "", penerima: initial?.penerima ?? "", departemenPenerima: initial?.departemenPenerima ?? "", keterangan: initial?.keterangan ?? "", kategori: initial?.kategori ?? "penyerahan", namaHrd: initial?.namaHrd ?? "", aset: (initial?.aset ?? []).map((item) => typeof item === "string" ? item : item.kode) } });
  async function submit(values: Values) { try { const url = initial ? `/api/surat/${encodeURIComponent(initial.nomor)}` : "/api/surat"; onSaved(await fetchJson<Surat>(url, { method: initial ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) })); } catch (cause) { setError("root", { message: cause instanceof Error ? cause.message : "Surat gagal disimpan." }); } }
  return <form onSubmit={handleSubmit(submit)} className="grid gap-5" noValidate><div className="grid gap-4 md:grid-cols-2"><Input label="Nama yang menyerahkan" error={errors.nama?.message} disabled={isSubmitting} {...register("nama")}/><Select label="Departemen penyerah" error={errors.departemen?.message} disabled={isSubmitting} {...register("departemen")}><option value="">Pilih departemen</option>{departments.map((item) => <option key={item}>{item}</option>)}</Select><Input label="Nama yang menerima" error={errors.penerima?.message} disabled={isSubmitting} {...register("penerima")}/><Select label="Departemen penerima" error={errors.departemenPenerima?.message} disabled={isSubmitting} {...register("departemenPenerima")}><option value="">Pilih departemen</option>{departments.map((item) => <option key={item}>{item}</option>)}</Select><Select label="Kategori" error={errors.kategori?.message} disabled={isSubmitting} {...register("kategori")}><option value="penyerahan">Penyerahan</option><option value="pengembalian">Pengembalian</option></Select><Input label="Nama HRD (opsional)" error={errors.namaHrd?.message} disabled={isSubmitting} {...register("namaHrd")}/></div><label className="grid gap-1.5 text-sm font-medium text-slate-700">Keterangan<textarea rows={4} disabled={isSubmitting} aria-invalid={Boolean(errors.keterangan)} className="rounded-lg border border-slate-300 bg-white p-3 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100 disabled:bg-slate-100" {...register("keterangan")}/>{errors.keterangan && <span role="alert" className="text-xs text-red-700">{errors.keterangan.message}</span>}</label><fieldset disabled={isSubmitting} className="grid gap-3"><legend className="text-sm font-medium text-slate-700">Aset terkait (maks. 50)</legend>{assets.length ? <div className="grid max-h-44 gap-2 overflow-auto rounded-lg border border-slate-200 p-3 sm:grid-cols-2">{assets.map((asset) => <label key={asset.kode} className="flex items-start gap-3 rounded-lg p-2 text-sm hover:bg-slate-50"><input type="checkbox" value={asset.kode} className="mt-1 size-4 accent-blue-700" {...register("aset")}/><span><strong className="block">{asset.nama}</strong><span className="text-slate-500">{asset.kode} · {asset.status}</span></span></label>)}</div> : <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Belum ada aset. Surat tetap dapat dibuat tanpa aset.</p>}</fieldset>{errors.root && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{errors.root.message}</p>}<div className="flex flex-wrap justify-end gap-3">{onCancel && <Button className="bg-white text-slate-700 ring-1 ring-slate-300 hover:bg-slate-50" onClick={onCancel} disabled={isSubmitting}>Batal</Button>}<Button type="submit" disabled={isSubmitting}><Save className="size-4"/>{isSubmitting ? "Menyimpan…" : initial ? "Simpan perubahan" : "Buat surat"}</Button></div></form>;
}
